Use graph instead of subgraph.
Otherwise dot reports this error:

..............Error: graph.dot:1: syntax error near line 1
context:  >>> subgraph <<<  RGL__AdjacencyGraph {